# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push: 
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        echo "${GITHUB_REF}"
        BRANCH_OR_TAG="$(echo "${GITHUB_REF}" | sed 's/refs\/heads\///g' | sed 's/refs\/tags\///g')"
        echo "BRANCH_OR_TAG=${BRANCH_OR_TAG}" >> $GITHUB_ENV
#    - name: Bump version and push tag
#      id: tag_version
#      uses: mathieudutour/github-tag-action@v5.3
#      with:
#        github_token: ${{ secrets.GIT_TOKEN }}
#        release_branches: master
#        tag_prefix: v
#

    - name: Production -- Generate Changelog
      if: contains(github.ref, '/tags/v')
      uses: scottbrenner/generate-changelog-action@master
      id: Changelog
      env:
        REPO: ${{ github.repository }}


    - name: Create a GitHub releases
      if: contains(github.ref, '/tags/v')
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        tag_name: ${{ env.BRANCH_OR_TAG }}
        release_name: Release ${{ env.BRANCH_OR_TAG }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
          ## Deployment Checklist
          - [ ] Ensure documentation is accurate
          - [ ] Ensure pyproject.toml links are accurate
          - [ ] Ensure readthedocs integration is working
          - [ ] Ensure version is correct
        #tag_name: ${{ steps.tag_version.outputs.new_tag }}
        #release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        #body: ${{ steps.tag_version.outputs.changelog }}

#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8

    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew

    # - name: Build with Gradle
    #   run: ./gradlew build

#    - name: Build and Push Docker Image
#      uses: mr-smithers-excellent/docker-build-push@v5
#      with:
#        image: rtdata/git-action-demo-app
#        registry: docker.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
    
